"""RuleBasedSampler — DAG-walk + plugin-dispatch sampler. No LLM.

Per-axis sampling method is declared in the `sampling_spec` block of the
persona_config. Native methods:
    marginal                 sample categorical from axis.marginal
    flag_marginal            independent Bernoulli per flag from axis.rates
    conditional_categorical  sample child cat from a joint table given parents
    conditional_flag_rate    Bernoulli per flag from a joint table given parents
    plugin                   call a region-specific function

Plugin signature (region-specific code under simulations/<sim>/derived/):
    def sample(rng, ctx, axis, persona_so_far, persona_config, **kwargs) -> Any

The vote field is generated by a separate post-DAG step that:
    1. Resolves welfare_dominant via the configured WelfareOverlapReducer
       (this also stamps persona_so_far["welfare_dominant"])
    2. Looks up each enabled vote-table row for the persona's parent value
    3. Blends rates via the configured VoteBlender
    4. Samples a party from the blended distribution
"""
from __future__ import annotations

import random
from typing import Any

from ...core.axis import Axis
from ...core.config import PersonaConfig, SimulationContext
from ...core.dag import DAG
from ...core.joint import Joint
from ...core.persona import Persona
from ..blending import make_vote_blender, make_welfare_overlap


def _bucket_lookup(value: Any, bucket_map: dict[str, list[str]] | None) -> Any | None:
    if not bucket_map:
        return value
    for bucket, leaves in bucket_map.items():
        if value in leaves:
            return bucket
    return None


class RuleBasedSampler:
    def __init__(
        self,
        ctx: SimulationContext,
        persona_config: PersonaConfig,
        *,
        seed: int | None = None,
    ):
        self.ctx = ctx
        self.config = persona_config
        self.rng = random.Random(seed)
        self.spec: dict[str, dict] = persona_config.get("sampling_spec", {}) or {}
        self.dag = DAG(ctx.axes, ctx.joints, extra_edges=self._extra_edges_from_spec())
        # Vote layer
        self.vote_enabled = persona_config.get("vote.enabled", True)
        self.vote_field = persona_config.get("vote.field_name", "vote_2019_LS")
        self.vote_inputs = persona_config.get("vote.blending.inputs", []) or []
        self.vote_blender = make_vote_blender(
            persona_config.get("vote.blending.method", "log_odds_mean")
        )
        self.welfare_reducer = make_welfare_overlap(
            persona_config.get("vote.welfare_overlap.method", "mean"),
            persona_config.get("vote.welfare_overlap.precedence"),
        )

    def _extra_edges_from_spec(self) -> dict[str, list[str]]:
        edges: dict[str, list[str]] = {}
        for axis_name, spec in (self.spec or {}).items():
            extra = spec.get("inputs") or spec.get("after")
            if extra:
                edges[axis_name] = list(extra)
        return edges

    # ---------------- Public API ----------------

    def sample_many(self, n: int) -> list[Persona]:
        return [self.sample_one(i) for i in range(n)]

    def sample_one(self, idx: int) -> Persona:
        fields: dict[str, Any] = {}
        for axis_name in self.dag.topo_order:
            axis = self.ctx.axis(axis_name)
            fields[axis_name] = self._sample_axis(axis, fields)
        if self.vote_enabled:
            fields[self.vote_field] = self._sample_vote(fields)
        return Persona(id=f"{self.config.set_name}_p{idx:04d}", fields=fields)

    # ---------------- Per-axis dispatch ----------------

    def _sample_axis(self, axis: Axis, persona_so_far: dict) -> Any:
        spec = self.spec.get(axis.name, {})
        method = spec.get("method")
        if method is None:
            method = {
                "partition": "marginal",
                "flag": "flag_marginal",
                "derived": "plugin",
            }.get(axis.kind)
        if method == "marginal":
            return self._marginal(axis)
        if method == "flag_marginal":
            return self._flag_marginal(axis)
        if method == "conditional_categorical":
            return self._conditional_categorical(axis, spec, persona_so_far)
        if method == "conditional_flag_rate":
            return self._conditional_flag_rate(axis, spec, persona_so_far)
        if method == "plugin":
            module = spec.get("module") or axis.module
            function = spec.get("function") or axis.function
            if not module or not function:
                raise ValueError(f"axis {axis.name!r}: plugin method needs module+function")
            fn = self.ctx.load_plugin(module, function)
            return fn(self.rng, self.ctx, axis, persona_so_far,
                      persona_config=self.config, **spec.get("kwargs", {}))
        raise ValueError(f"axis {axis.name!r}: unknown sampling method {method!r}")

    # ---------------- Native sampling primitives ----------------

    def _marginal(self, axis: Axis) -> str:
        cats = axis.categories or []
        weights = [axis.marginal[c] for c in cats]
        return self.rng.choices(cats, weights=weights, k=1)[0]

    def _flag_marginal(self, axis: Axis) -> dict[str, bool]:
        out: dict[str, bool] = {}
        for flag in (axis.flags or []):
            rate = float((axis.rates or {}).get(flag, 0.0)) / 100.0
            out[flag] = self.rng.random() < rate
        return out

    def _conditional_categorical(self, axis: Axis, spec: dict, fields: dict) -> str:
        joint = self.ctx.joint(spec["joint"])
        parent_value = self._lookup_parent_value(joint, fields)
        row = joint.table.get(parent_value, {})
        if not row:
            return self._marginal(axis)
        cats = list(row.keys())
        weights = list(row.values())
        sampled = self.rng.choices(cats, weights=weights, k=1)[0]
        # Optional "Other" expansion via a sub-marginal.
        oe = joint.child_other_expansion_categories
        if oe and sampled == "Other":
            target_axis = self.ctx.axis(joint.child_other_expansion_axis or axis.name)
            sub_pcts = [target_axis.marginal[c] for c in oe]
            sampled = self.rng.choices(oe, weights=sub_pcts, k=1)[0]
        return sampled

    def _conditional_flag_rate(self, axis: Axis, spec: dict, fields: dict) -> dict[str, bool]:
        joint = self.ctx.joint(spec["joint"])
        parent_value = self._lookup_parent_value(joint, fields)
        row = joint.table.get(parent_value, {})
        out: dict[str, bool] = {}
        for flag, rate in row.items():
            out[flag] = self.rng.random() < (float(rate) / 100.0)
        return out

    def _lookup_parent_value(self, joint: Joint, fields: dict):
        if len(joint.parents) == 1:
            v = fields.get(joint.parents[0])
            if joint.parents[0] == "caste" and joint.caste_bucket_map:
                v = _bucket_lookup(v, joint.caste_bucket_map)
            return v
        # multi-parent → return tuple
        return tuple(fields.get(p) for p in joint.parents)

    # ---------------- Vote layer ----------------

    def _sample_vote(self, fields: dict) -> str:
        per_table: dict[str, dict[str, float]] = {}
        weights: dict[str, float] = {}
        all_parties: set[str] = set()

        # Welfare reducer pass: populates welfare_dominant (canonical label) +
        # may emit a pre-blended distribution that bypasses table lookup.
        welfare_label = None
        welfare_pre_blend = None
        for inp in self.vote_inputs:
            if inp.get("parent") == "welfare_dominant":
                wj = self.ctx.joint(inp["table"])
                flags = fields.get("welfare_exposure", {})
                label, dist = self.welfare_reducer.reduce(
                    flags, wj.table, wj.parties or []
                )
                welfare_label = label
                welfare_pre_blend = dist
                # Stamp a stable label for verifier (drop composite "+" labels).
                fields["welfare_dominant"] = label if "+" not in label else "None"

        for inp in self.vote_inputs:
            joint = self.ctx.joint(inp["table"])
            parent = inp["parent"]
            w = float(inp.get("weight", 1.0))
            if parent == "welfare_dominant":
                if welfare_pre_blend is not None:
                    per_table[inp["table"]] = welfare_pre_blend
                else:
                    row = joint.table.get(welfare_label, {})
                    if row:
                        per_table[inp["table"]] = row
                weights[inp["table"]] = w
            else:
                pv = fields.get(parent)
                if parent == "caste" and joint.caste_bucket_map:
                    pv = _bucket_lookup(pv, joint.caste_bucket_map)
                if pv is None:
                    continue
                row = joint.table.get(pv, {})
                if not row:
                    continue
                per_table[inp["table"]] = row
                weights[inp["table"]] = w
            all_parties.update(joint.parties or [])

        parties = sorted(all_parties) or ["BJP", "AITC", "INC", "LF", "Other"]
        if not per_table:
            return self.rng.choice(parties)
        blended = self.vote_blender.blend(per_table, weights, parties)
        return self.rng.choices(parties, weights=[blended[p] for p in parties], k=1)[0]
