"""Derived-axis stub for `abhishek_loyalty` (AC 143).

Auto-generated by scripts/scaffold_ac_baseline_runtime.py. Returns the first
category of the axis as a placeholder. Replace with real logic when the AC's
narrative model needs this axis populated meaningfully (the partial verifier
ignores it for population validation either way — derived axes are not part
of the calibrated_2019 marginal/joint set).
"""
from __future__ import annotations


def compute(rng, ctx, axis, persona, persona_config=None, **kwargs):
    cats = axis.categories or []
    if not cats:
        return None
    return cats[0]
